- name: Install fio
  become: yes
  apt: name=fio

- name: Load profile
  include_vars:
    file: "{{ (playbook_dir, 'profiles', profile_name + '.yaml') | path_join }}"
    name: profile

- import_tasks: kernel_settings.yaml

- name: Create a jobs directory on the target host
  file:
    path: "{{ (ansible_user_dir, 'fio_jobs') | path_join }}"
    state: directory
    mode: '0755'

- name: Copy fio job file to target host 
  template:
    src: profile.fio.j2
    dest: "{{ (ansible_user_dir, 'fio_jobs', profile_name + '.fio') | path_join }}"

- name: Create an fio output directory on the target host
  file:
    path: "{{ (ansible_user_dir, 'fio_output') | path_join }}"
    state: directory
    mode: '0755'

- name: Run fio jobs
  command: >
    fio 
      --filename=fio_data 
      --output-format=json+ 
      --output="{{ (ansible_user_dir, 'fio_output', profile_name + '.json') | path_join }}"
    "{{ (ansible_user_dir, 'fio_jobs', profile_name + '.fio') | path_join }}"
  args:
    chdir: "{{ run_dir }}"

- name: Copy fio output file from host
  fetch:
    src: "{{ (ansible_user_dir, 'fio_output', profile_name + '.json') | path_join }}"
    dest: "{{ (playbook_dir, 'output') | path_join }}"

- name: Delete fio data from target
  file:
    path: "{{ (run_dir, 'fio_data') | path_join }}"
    state: absent

# vim: set ft=yaml.ansible:
