- name: Set up and run FIO jobs
  hosts: f2_big_disk_vms, f4_big_disk_vms, f8_big_disk_vms, f16_big_disk_vms, f32_big_disk_vms, f48_big_disk_vms, f64_big_disk_vms, f72_big_disk_vms
  vars:
    workload_id: 1
    workload_size: large
  tasks:
  - name: Read the settings from CSV
    community.general.read_csv:
      path: settings.csv
    register: settings
    delegate_to: localhost

  - name: Run fio role for each specified configuration
    include_role:
      name: loop_fio
    loop: "{{ settings.list }}"
    loop_control:
      extended: yes

# vim: set ft=yaml.ansible:
