- name: Create the VM in Azure
  hosts: localhost
  roles: [azure_vm]
  tasks:
  - name: Reload Ansible's inventory file
    meta: refresh_inventory

- name: Do initial setup on the remote host
  hosts: azure_vm
  tasks:
  - import_role:
      name: azure_vm
      tasks_from: remote
