- name: Create the VM in Azure
  hosts: localhost
  tasks:
  - vars:
      vm_ansible_name: vm001
      vm_suffix: 001
      vm_disk_size_gb: 8192
      vm_instance_type: Standard_F16s_v2
    import_role:
      name: vm

  - name: Reload Ansible's inventory file
    meta: refresh_inventory

- name: Remote Setup
  hosts: vm001
  tasks:
  - name: Upgrade the Kernel Version
    import_role:
      name: kernel
      tasks_from: custom_upgrade

  - name: Mount and Format the disk
    import_role:
      name: data_disk

  - name: Trim the filesystem
    include_role:
      name: data_disk
      tasks_from: trim

# vim: set ft=yaml.ansible:
