- name: Remote Disk Teardown
  hosts: vm001
  tasks:
  - name: Unmount the Disk
    import_role:
      name: data_disk
      tasks_from: unmount

- name: Detach and Delete a Disk in Azure
  hosts: localhost
  tasks:
  - vars:
      vm_ansible_name: vm001
      vm_suffix: 001
    import_role:
      name: vm
      tasks_from: teardown
 

# vim: set ft=yaml.ansible:
