- name: Remote Disk Teardown
  hosts: f2_small_disk_vms, f4_small_disk_vms, f8_small_disk_vms,f16_small_disk_vms,f2_big_disk_vms, f4_big_disk_vms, f8_big_disk_vms, f16_big_disk_vms
  tasks:
  - name: Unmount the Disk
    import_role:
      name: data_disk
      tasks_from: teardown

- name: Detach and Delete a Disk in Azure
  hosts: localhost
  tasks:
  - vars:
      vm_ansible_name: vm001
      vm_suffix: 001
    include_role:
      name: vm
      tasks_from: teardown

  - vars:
      vm_ansible_name: vm002
      vm_suffix: 002
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm003
      vm_suffix: 003
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm004
      vm_suffix: 004
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm005
      vm_suffix: 005
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm006
      vm_suffix: 006
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm007
      vm_suffix: 007
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm008
      vm_suffix: 008
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm009
      vm_suffix: 009
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm010
      vm_suffix: 010
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm011
      vm_suffix: 011
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm012
      vm_suffix: 012
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm098
      vm_suffix: 098
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm099
      vm_suffix: 099
    import_role:
      name: vm
      tasks_from: teardown

  - vars:
      vm_ansible_name: vm013
      vm_suffix: 013
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm014
      vm_suffix: 014
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm015
      vm_suffix: 015
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm016
      vm_suffix: 016
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm017
      vm_suffix: 017
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm018
      vm_suffix: 018
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm019
      vm_suffix: 019
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm020
      vm_suffix: 020
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm021
      vm_suffix: 021
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm022
      vm_suffix: 022
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm023
      vm_suffix: 023
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm024
      vm_suffix: 024
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm100
      vm_suffix: 100
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm101
      vm_suffix: 101
    import_role:
      name: vm
      tasks_from: teardown

  - vars:
      vm_ansible_name: vm025
      vm_suffix: 025
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm026
      vm_suffix: 026
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm027
      vm_suffix: 027
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm028
      vm_suffix: 028
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm029
      vm_suffix: 029
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm030
      vm_suffix: 030
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm031
      vm_suffix: 031
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm032
      vm_suffix: 032
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm033
      vm_suffix: 033
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm034
      vm_suffix: 034
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm035
      vm_suffix: 035
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm036
      vm_suffix: 036
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm102
      vm_suffix: 102
    import_role:
      name: vm
      tasks_from: teardown
  - vars:
      vm_ansible_name: vm103
      vm_suffix: 103
    import_role:
      name: vm
      tasks_from: teardown

  - vars:
      vm_ansible_name: vm037
      vm_suffix: 037
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm038
      vm_suffix: 038
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm039
      vm_suffix: 039
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm040
      vm_suffix: 040
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm041
      vm_suffix: 041
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm042
      vm_suffix: 042
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm043
      vm_suffix: 043
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm044
      vm_suffix: 044
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm045
      vm_suffix: 045
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm046
      vm_suffix: 046
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm047
      vm_suffix: 047
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm048
      vm_suffix: 048
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm104
      vm_suffix: 104
    import_role:
      name: vm
  - vars:
      vm_ansible_name: vm105
      vm_suffix: 105
    import_role:
      name: vm

# vim: set ft=yaml.ansible:
