- name: Unarchive Linux tarball
  become: yes
  unarchive:
    src: linux_512.tar.gz
    dest: "/boot"
    remote_src: no
    extra_opts:
    - --strip-components=1

- name: Unarchive the modules
  become: yes
  unarchive:
    src: /boot/5.12.0-rc2+.tar.gz
    dest: /lib/modules
    remote_src: yes

- name: Delete modules archive
  become: yes
  file:
    path: /boot/5.12.0-rc2+.tar.gz
    state: absent

- name: Update grub config
  become: yes
  command: update-grub

- name: Print kernel version before reboot
  debug:
    var: ansible_facts['kernel']

- name: Reboot machine with newer kernel
  become: yes
  reboot:
  when: ansible_facts['kernel'] is version('5.12', '<')
  register: rebooted

- name: Run facts module to get latest facts
  setup:
  when: rebooted is not skipped

- name: Print kernel version after reboot
  debug:
    var: ansible_facts['kernel']
  when: rebooted is not skipped

- name: Add the bfq module
  become: yes
  community.general.modprobe:
    name: bfq

# vim: set ft=yaml.ansible:
