host:
  instance_size: Standard_F32s_v2

disk:
  size: 2000

# While it is inconvenient to require playbook users to remember to set
# this hard-coded value correctly, there is no reasonable way I could
# devise to parameterize this given that the profiles are host agnostic
device: "/dev/disk/azure/scsi1/lun1"

kernel:
  io_scheduler: mq-deadline
  max_sectors_kb: 128
  read_ahead_kb: 4096
  queue_depth: 64
  nr_requests: 128

fio:
  bs: 8k
  iodepth: 8
  rw: write
  runtime: 10
