- name: Create /etc/ansible/facts.d
  become: yes
  file: name=/etc/ansible/facts.d state=directory

- name: Copy over custom fact on device to help disk_kernel role
  become: yes
  template:
    dest: /etc/ansible/facts.d/disk_kernel_device.fact
    src: disk_kernel_device.fact.j2
    mode: "0755"
  register: disk_kernel_device_fact_file

- setup:
  when: disk_kernel_device_fact_file.changed

# TODO: would prefer to use the device itself and not a partition,
# but couldn't get it to mount successfully with just the device
- name: Install parted and fdisk
  become: yes
  apt:
    pkg:
      - parted
      - fdisk

- name: Partition and format the disk
  become: yes
  parted:
    device: "{{ vm_data_disk_specs['device']|quote }}"
    label: gpt
    fs_type: ext4
    name: data
    state: present
    number: 1
  register: formatted_disk

- name: Unmount the filesystem in case it is mounted already
  become: yes
  ansible.posix.mount:
    path: "{{ data_disk_mount_dir }}"
    state: absent

- name: Format the disk and build the filesystem
  become: yes
  filesystem:
    fstype: ext4
    dev: "{{ formatted_disk.disk.dev }}{{ formatted_disk.partitions[0].num }}"
    opts: "-E lazy_itable_init=0,lazy_journal_init=0"
    force: yes

- name: Given formatted disk partition information, get UUID
  become: yes
  command: blkid -s UUID -o value "{{ formatted_disk.disk.dev }}{{ formatted_disk.partitions[0].num }}"
  register: uuid_data_disk_partition

- name: Make a directory for the filesystem
  become: yes
  file: path="{{ data_disk_mount_dir }}" state=directory

- name: Mount the filesystem
  become: yes
  ansible.posix.mount:
    path: "{{ data_disk_mount_dir }}"
    src: UUID="{{ uuid_data_disk_partition.stdout }}"
    fstype: ext4
    state: mounted

- name: Change permissions and ownership of mounted disk
  become: yes
  file:
    path: "{{ data_disk_mount_dir }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}" 
    mode: '0755'

# vim: set ft=yaml.ansible:
