# names chosen according to recommendations in
# https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging
# with consideration of naming scope

- name: Get my IP address"
  tags: test_ip
  community.general.ipify_facts:
  register: ipify_public_ip

- name: Generate OpenSSH public key
  openssh_keypair:
    path: "{{ privatekey | default(playbook_dir + '/id') }}"
    type: ed25519
    regenerate: never
  register: keypair

- name: Create a Resource Group
  azure_rm_resourcegroup:
    name: "{{ resource_group_name }}"
    location: "{{ location }}"
  register: resource_group

- name: Create a Network Security Group
  azure_rm_securitygroup:
    resource_group: "{{ resource_group.state.name }}"
    name: nsg-sshallow-001
    purge_default_rules: yes
    purge_rules: yes
  register: security_group

- name: Create a Virtual Network
  azure_rm_virtualnetwork:
    name: "vnet-incubator-{{ location }}-001"
    resource_group: "{{ resource_group.state.name }}"
    address_prefixes_cidr:
    - "10.0.0.0/16"
  register: virtual_network

- name: Create a Subnet in the Virtual Network
  azure_rm_subnet:
    name: "snet-incubator-{{ location }}-001"
    resource_group: "{{ resource_group.state.name }}"
    virtual_network: "{{ virtual_network.state.name }}"
    address_prefix_cidr: "10.0.0.0/24"
    security_group: "{{ security_group.state.name }}"
  register: subnet

- name: Create a Public IP Address
  azure_rm_publicipaddress:
    name: "pip-vmiobench-{{ location }}-001"
    resource_group: "{{ resource_group.state.name }}"
    allocation_method: static
  register: public_ip_address

- name: Create a Network Interface
  azure_rm_networkinterface:
    name: "nic-01-vmiobench-incubator-001"
    resource_group: "{{ resource_group.state.name }}"
    virtual_network: "{{ virtual_network.state.name }}"
    security_group: "{{ security_group.state.name }}"
    subnet_name: "{{ subnet.state.name }}"
    ip_configurations:
    - name: "vmiobench-ipconfig-001"
      public_ip_address_name: "{{ public_ip_address.state.name }}"
      primary: True
  register: network_interface

- name: Create a Storage Account
  azure_rm_storageaccount:
    name: "stvmiobench{{ location }}001"
    resource_group: "{{ resource_group.state.name }}"
    account_type: Premium_LRS
    force_delete_nonempty: yes
    kind: StorageV2
  register: storage_account

- name: Create a VM
  azure_rm_virtualmachine:
    admin_username: "{{ ansible_user_id }}"
    ssh_password_enabled: false
    name: vmiobench-001
    resource_group: "{{ resource_group.state.name }}"
    vm_size: "{{ instance_size }}"
    virtual_network: "{{ virtual_network.state.name }}"
    subnet: "{{ subnet.state.name }}"
    network_interfaces: "{{ network_interface.state.name }}"
    # not supported for Premium_LRS
    # boot_diagnostics:
    #   enabled: yes
    #   storage_account: "{{ storage_account.state.name }}"
    managed_disk_type: Premium_LRS
    image:
      offer: debian-10
      publisher: Debian
      sku: 10
      version: latest
    ssh_public_keys:
    - path: "/home/{{ ansible_user_id }}/.ssh/authorized_keys"
      key_data: "{{ keypair.public_key }}"
  register: vm

# not able to attach storage to VM currently due to bug
# https://github.com/ansible-collections/azure/issues/146
# after bug is resolved, will be able to set managed_disk_id in VM
# and managed_by in data disk
# until then, need to manually attach the disk
- name: Create a Data Disk
  azure_rm_manageddisk:
    name: dd-001
    resource_group: "{{ resource_group.state.name }}"
    create_option: empty
    storage_account_type: Premium_LRS
    os_type: linux
    # TODO: consider parameterizing
    attach_caching: ''
    disk_size_gb: "{{ disk_size }}"
    # managed-by doesn't work. error says:
    # Unsupported parameters for (azure_rm_manageddisk) module:
    # managed-by Supported parameters include: ad_user,
    # adfs_authority_url, api_profile, append_tags, attach_caching,
    # auth_source, cert_validation_mode, client_id, cloud_environment,
    # create_option, disk_size_gb, location, lun, managed_by, name,
    # os_type, password, profile, resource_group, secret, source_uri,
    # state, storage_account_type, subscription_id, tags, tenant, zone
    #managed-by: vmiobench-001

- name: VM's public IP address
  debug: var=public_ip_address.state.ip_address

- name: Update Ansible's inventory file
  template:
    dest: "{{ playbook_dir }}/hosts"
    src: hosts.j2

# Followed these instructions https://docs.microsoft.com/en-us/azure/virtual-machines/linux/add-disk
# Note that because this is done directly through the Azure CLI, we do not have the idempotency that Ansible usually provides.
# If the disk is already attached, this will error out
# This is unfortunate but unavoidable due to the bug
# If you have to run this playbook when you have already attached a disk at lun 1, run the playbook with --skip_tags="disk-attach" (or detach the disk)
- name: Attach the Data Disk to the VM
  command: >
    az vm disk attach
    -g "{{ resource_group_name | quote }}"
    --vm-name vmiobench-001
    --name dd-001
    --lun 1
  tags: disk-attach

- name: Print Azure VM disk device
  debug:
    msg: "Azure VM disk attached. Use '/dev/disk/azure/scsi1/lun1' for device name in future tasks requiring device name"
